theme:
  background-color: "#fff"
  container-border-radius: 0.4em
  primary-text-color: "#000"
  error-text-color: "#f00"
  hint-text-color: "#333"
  button:
    btn-background-color: '#111'
    btn-disabled-background-color: '#111'
    btn-disabled-opacity: 0.5
  title:
    large-font-family: Helvetica Neue
    large-font-size: 1.35em
    large-font-weight: 600
    large-line-height: 2em
    large-letter-spacing: 0.05em
    large-text-transform: uppercase
  sub-title:
    medium-text-size: 1.1em
    medium-font-weight: 300
  content: 
    content-width: 500px
    content-padding: 2.1em
  placeholder: 
    placeholder-text-transform: uppercase
    placeholder-font-size: inherit
    placeholder-color: "#111"
  text-input:
    text-input-margin: 1.1em
  image:
    image-padding: 1em
    image-size: 50%
    image-url: url('https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569')

page-landing:
  image: url("https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569")
  image-width: 30%
page-register:
  image: url("https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569")
  image-width: 30%


