theme:
  background-color: "#fff"
  title:
    title-text-transform: uppercase
    title-font-size: 24px
    title-font-family: '"Helvetica Neue", Arial, "Lucida Grande", sans-serif'
    title-letter-spacing: 0.5px
  main-text-color: "#111"
  align-items: center
  image: none
  box-model: #dans theme.
    margin: "0.1em"
    padding: "0.1em"
    border: "none" # 1px solid red; | ...
  fonts: # dans theme
    titles-family:  "serif" # cursive | Georgia, serif | ...
    subtitle-family: "..."
    content-family: "serif" # cursive | Georgia, serif | ...
    placeholder-text-transform: uppercase
  

page-landing:
  image: url("https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569")

page-register:
  image: url("https://cdn.shopify.com/s/files/1/2598/9270/files/Chien-16.png?v=1595509535")


