theme:
  align-items: center
  background-color: "#fff"
  image: none
  main-text-color: "#000"
  secondary-text-color: "#000"
  tertiary-text-color: "#000"
  error-text-color: "#f00"
  hint-text-color: "#333"
  primary-color: "#000"
  secondary-color: "#000"
  tertiary-color: "#777"
  large-text-size: 2.5em
  medium-text-size: 1.8em
  normal-text-size: 16px
  small-text-size: 0.8em
  title:
    title-text-transform: uppercase
    title-font-size: 24px
    title-font-family: '"Helvetica Neue", Arial, "Lucida Grande", sans-serif'
    title-letter-spacing: 0.5px
    title-font-weight: 600
    title-line-height: 36px
  box-model: #dans theme.
    margin: "0.1em"
    padding: "0.1em"
    border: "none" # 1px solid red; | ...
  fonts: # dans theme
    titles-family:  "serif" # cursive | Georgia, serif | ...
    subtitle-family: "..."
    content-family: "serif" # cursive | Georgia, serif | ...
    placeholder-text-transform: uppercase
page-landing:
  image: url("https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569")
  image-width: 30%
page-register:
  image: url("https://cdn.shopify.com/s/files/1/0407/2855/9766/files/Ellipse_3_1.png?v=1596746569")
  image-width: 30%


