theme:
  container-border-radius: 0.2em
  container-bg-color: rgba(90, 91, 91, 0.4)
  container-bg-image: url("https://images-na.ssl-images-amazon.com/images/I/81Dpm0mr03L.jpg")
  content-bg-color: "#fff"
  primary-text-color: "#0d3c32"
  error-text-color: "#f00"
  hint-text-color: "#333"
  button:
    btn-bg-color: '#007266'
    btn-disabled-bg-color: '#007266'
    btn-disabled-opacity: 0.5
  title:
    large-font-family: Burgess
    large-font-size: 3.1em
    large-font-weight: 300
    large-line-height: 1.1em
    large-letter-spacing: 0.05em
    large-text-transform: none
  sub-title:
    medium-text-size: 0.98em
    medium-font-weight: 300
  content: 
    content-width: 530px
    content-padding: 1.5em
  placeholder: 
    placeholder-text-transform: uppercase
    placeholder-font-size: 1.1em
    placeholder-color: inherit
  text-input:
    text-input-margin: 0.9em
  image:
    image-padding: 0
    image-size: 40%
    image-url: none

page-landing:
  image: none
  image-width: 40%

page-register:
  image: none
  image-width: 40%
