theme:
  common:
    background-color: "#fff"
    main-text-color: "#111"
    large-text-size: 1.875rem
    align-items: center
    landing_image: url("https://tinyurl.com/yxqebeg7")
    box-model: #dans theme.
      margin: "1em 0.4em"
      padding: "0.8em"
      border: "none" # 1px solid red; | ...
    fonts: # dans theme
      titles-family:  "serif" # cursive | Georgia, serif | ...
      subtitle-family: "..."
      content-family: "serif" # cursive | Georgia, serif | ...
