
title: "My title"
title2: "My title2"
name: "My name is anton"
loginRegister: "Connexion / Inscription"
enterYourEmailToContinue: "Renseignez votre adresse email pour continuer."
yourEmail: "Votre email"
signIn: "Se Connecter"
signUp: "S'inscrire"
fillInfoToCreateAccount: Renseignez vos informations pour créer votre compte Franklin.
login: "Connexion"
enterEmailPswToConnect: Renseignez votre adresse email et votre mot de passe pour vous connecter.
validate: "Valider"


