hasGender: true
hasSocialLogin: false
hasBirthDate: true
hasPasswordVerification: false
isPopover: true

createAccount: Inscription
loginRegister: "Login to my account"
enterYourEmailToContinue: "Enter your e-mail and password:"
yourEmail: "Votre Courriel"
signIn: "Se Connecter"
signUp: "S'inscrire"
fillInfoToCreateAccount: Renseignez vos informations pour créer votre compte Franklin.
login: "Connexion"
enterEmailPswToConnect: Renseignez votre adresse email et votre mot de passe pour vous connecter.
validate: "Valider"
login-register: Connexion / Inscription
yourFirstName: Prénom
yourLastName: Nom
yourPassword: Votre mot de passe
confirmYourPassword: Confirmez votre mot de passe
subscribeNewsletter: Je m'inscris à la newsletter
