hasGender: false
hasSocialLogin: false
hasBirthDate: false
hasPasswordVerification: false
isPopover: true

createAccount: Create your account
loginRegister: "Login to my account"
enterYourEmailToContinue: "Enter your e-mail and password:"
yourEmail: "Votre Courriel"
signIn: "Se Connecter"
signUp: "S'inscrire"
fillInfoToCreateAccount: "Please fill in the information below:"
login: "Connexion"
enterEmailPswToConnect: Enter your e-mail and password:.
recoverPsw: Recover password
validate: "Valider"
login-register: Connexion / Inscription
yourFirstName: Prénom
yourLastName: Nom
yourPassword: Votre mot de passe
confirmYourPassword: Confirmez votre mot de passe
subscribeNewsletter: Je m'inscris à la newsletter
isNewCustomer: New customer?
doYouLostPsw: Lost password?
