const themeName = process.argv.slice(-1)[0];
const yaml = require("js-yaml");
const fs = require("fs");
const idsPage = fs.readFileSync("./src/configs/pages-id.yml", "utf8");
const data = fs.readFileSync(`./src/configs/${themeName}-style.yml`, "utf8");
const yamlStyle = yaml.load(data);
const { APP_ID, LANDING_ID, REGISTER_ID } = yaml.load(idsPage);
const cssMapping = {
    // theme: APP_ID,
    // "page-landing": LANDING_ID,
    // "page-register": REGISTER_ID,
};
const getCssVars = (_yamlStyle) => {
    let cssVariables = "";
    (function traverse(obj, key) {
        if (obj !== null && typeof obj == "object") {
            Object.entries(obj).forEach(([key, value]) => traverse(value, key));
        } else cssVariables += `\t--${key}: ${obj};\n`;
    })(_yamlStyle);
    return cssVariables;
};

const getJsonVars = (_yamlStyle) => {
    let json = {};
    (function traverse(obj, key) {
        if (obj !== null && typeof obj == "object") {
            Object.entries(obj).forEach(([key, value]) => traverse(value, key));
        } else json[`--${key}`] = obj;
    })(_yamlStyle);
    return json;
};

let cssVars = "/*This file is autogenerated (see yaml2json.js)*/\n";
let jsonVars = { _comment: "This file is autogenerated (see yaml2json.js)" };
(() => {
    const cssSelectors = Reflect.ownKeys(yamlStyle);
    cssSelectors.forEach((scope) => {
        jsonVars[scope] = getJsonVars(yamlStyle[scope]);
        cssVars += cssMapping[scope]
            ? `#${cssMapping[scope]}{\n\t`
            : `.${scope} {\n\t`;
        cssVars += `${getCssVars(yamlStyle[scope]).trim()}\n}\n`;
    });
})();

fs.writeFile("src/styles/custom.scss", cssVars, () => {});
fs.writeFile(
    "src/styles/custom.json",
    JSON.stringify(jsonVars, null, "\t"),
    () => {}
);

const writeJsonText = () => {
    const data = fs.readFileSync(`./src/configs/${themeName}-text.yml`, "utf8");
    fs.writeFile(
        "src/styles/text.json5",
        JSON.stringify(yaml.load(data), null, "\t"),
        () => {}
    );
};

writeJsonText();
