const yaml = require("js-yaml");
const fs = require("fs");
const idsPage = fs.readFileSync("./src/configs/pages-id.yml", "utf8");
const data = fs.readFileSync("./src/configs/style.yml", "utf8");
const yamlStyle = yaml.load(data);
const { APP_ID } = yaml.load(idsPage);

const createCssVars = () => {
    let cssVariables = `/* This file is autogenerated by "yarn build"*/\n#${APP_ID} {\n`;
    (function traverse(obj, key) {
        if (obj !== null && typeof obj == "object") {
            Object.entries(obj).forEach(([key, value]) => {
                traverse(value, key);
            });
        } else cssVariables += `\t--${key}: ${obj};\n`;
    })(yamlStyle);

    return `${cssVariables}}`;
};

fs.writeFile("src/styles/custom.css", `${createCssVars()}`, () => {});
