const themeName = process.argv.slice(-1)[0];
const yaml = require("js-yaml");
const fs = require("fs");
const data = fs.readFileSync(`./src/configs/${themeName}-style.yml`, "utf8");
const yamlStyle = yaml.load(data);

//TODO it needs code refactoring
const getJsonVars = (_yamlStyle) => {
    let json = {};
    (function traverse(obj, key) {
        if (obj !== null && typeof obj == "object") {
            Object.entries(obj).forEach(([key, value]) => traverse(value, key));
        } else json[`--${key}`] = obj;
    })(_yamlStyle);
    return json;
};

let jsonVars = { _comment: "This file is autogenerated (see yaml2json.js)" };
(() => {
    const cssSelectors = Reflect.ownKeys(yamlStyle);
    cssSelectors.forEach((scope) => {
        jsonVars[scope] = getJsonVars(yamlStyle[scope]);
    });
})();

fs.writeFile(
    "src/styles/custom.json",
    JSON.stringify(jsonVars, null, "\t"),
    () => {}
);

const writeJsonText = () => {
    const data = fs.readFileSync(`./src/configs/${themeName}-text.yml`, "utf8");
    fs.writeFile(
        "src/styles/text.json5",
        JSON.stringify(yaml.load(data), null, "\t"),
        () => {}
    );
};

writeJsonText();
